<a href="https://colab.research.google.com/github/Apekshya175/AI-ML/blob/main/Worksheet0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Exercise on Functions:

Create a Python program that converts between different units of measurement.



In [ ]:
def convert(option, num):
    """
    Converts units based on the selected option.

    Parameters:
    option (int): conversion option selected by the user
    num (float): value to convert

    Returns:
    float: converted value
    """

    if option == 1:
        return num * 3.28
    elif option == 2:
        return num / 3.28
    elif option == 3:
        return num * 2.2
    elif option == 4:
        return num / 2.2
    elif option == 5:
        return num * 0.26
    elif option == 6:
        return num / 0.26
    else:
        return None


print("Unit Converter")

print("1. Meter to Feet")
print("2. Feet to Meter")
print("3. Kg to Pounds")
print("4. Pounds to Kg")
print("5. Liter to Gallon")
print("6. Gallon to Liter")

try:
    option = int(input("Enter option: "))
    num = float(input("Enter value: "))

    ans = convert(option, num)

    if ans is None:
        print("Unsupported conversion option.")
    else:
        print("Converted value is:", ans)

except ValueError:
    print("Invalid input. Please enter numeric values.")

Unit Converter
1. Meter to Feet
2. Feet to Meter
3. Kg to Pounds
4. Pounds to Kg
5. Liter to Gallon
6. Gallon to Liter
Enter option: 3
Enter value: 1000
Converted value is: 2200.0


Create a Python program that performs various mathematical operations on a list of numbers.

In [ ]:

def find_sum_list(nums):
    """
    calculate sum of numbers in list
    nums: list of numbers
    return: total sum
    """
    total = 0
    for n in nums:
        total = total + n
    return total


def find_avg_list(nums):
    """
    calculate average of numbers in list
    nums: list of numbers
    return: average value
    """
    total = find_sum_list(nums)
    return total / len(nums)


def find_max_list(nums):
    """
    find largest number in list
    nums: list of numbers
    return: maximum number
    """
    m = nums[0]
    for n in nums:
        if n > m:
            m = n
    return m


def find_min_list(nums):
    """
    find smallest number in list
    nums: list of numbers
    return: minimum number
    """
    m = nums[0]
    for n in nums:
        if n < m:
            m = n
    return m


print("Simple list calculator")
print("opt1 find sum ")
print("opt2 find average")
print("opt3 find max")
print("opt4 find min")

try:
    op = int(input("choose operation: "))
    text = input("type numbers separated by space: ")

    parts = text.split()
    nums = []

    for p in parts:
        nums.append(float(p))

    if len(nums) == 0:
        print("you did not enter any numbers")

    elif op == 1:
        print("sum =", find_sum_list(nums))

    elif op == 2:
        print("average =", find_avg_list(nums))

    elif op == 3:
        print("max number =", find_max_list(nums))

    elif op == 4:
        print("min number =", find_min_list(nums))

    else:
        print("invalid operation")



except ValueError:
    print("please enter numbers only")

Simple list calculator
opt1 find sum 
opt2 find average
opt3 find max
opt4 find min
choose operation: 2
type numbers separated by space: 4 5 6 7 
average = 5.5


Exercise on List Manipulation:

In [ ]:
# get every other element
def extract_every_other(lst):
    return lst[::2]

# get sublist from start to end
def get_sublist(lst, start, end):
    return lst[start:end+1]

# reverse the list
def reverse_list(lst):
    return lst[::-1]

# remove first and last items
def remove_first_last(lst):
    return lst[1:-1]

# get first n items
def get_first_n(lst, n):
    return lst[:n]

# get last n items
def get_last_n(lst, n):
    return lst[-n:]

# reverse skipping every second element
def reverse_skip(lst):
    return lst[-2::-2]


# testing with my own random list
my_list = [11, 7, 23, 5, 19, 14]
print("Every other element :", extract_every_other(my_list))
print("Sublist from index 2 to 4 :", get_sublist(my_list, 2, 4))
print("Reversed list :", reverse_list(my_list))
print("Without first & last :", remove_first_last(my_list))
print("First 3 items :", get_first_n(my_list, 3))
print("Last 2 items :", get_last_n(my_list, 2))
print("Reverse skipping every second :", reverse_skip(my_list))

Every other element : [11, 23, 19]
Sublist from index 2 to 4 : [23, 5, 19]
Reversed list : [14, 19, 5, 23, 7, 11]
Without first & last : [7, 23, 5, 19]
First 3 items : [11, 7, 23]
Last 2 items : [19, 14]
Reverse skipping every second : [19, 23, 11]


Exercise on Nested List

In [ ]:

def flatten(lst):
    result = []
    for sub in lst:
        for x in sub:
            result.append(x)
    return result

def access_nested_element(lst, idxs):
    temp = lst
    for i in idxs:
        temp = temp[i]
    return temp

def sum_nested(lst):
    total = 0
    for x in lst:
        if isinstance(x,list):
            total += sum_nested(x)
        else:
            total += x
    return total

def remove_element(lst, elem):
    new_lst = []
    for sub in lst:
        new_sub = []
        for x in sub:
            if x != elem:
                new_sub.append(x)
        new_lst.append(new_sub)
    return new_lst

# find max element
def find_max(lst):
    max_val = float('-inf')
    for x in lst:
        if isinstance(x,list):
            val = find_max(x)
        else:
            val = x
        if val > max_val:
            max_val = val
    return max_val

# count occurrences of elem
def count_occurrences(lst, elem):
    count = 0
    for x in lst:
        if isinstance(x,list):
            count += count_occurrences(x, elem)
        else:
            if x == elem:
                count += 1
    return count

# deep flatten any depth
def deep_flatten(lst):
    flat = []
    for x in lst:
        if isinstance(x,list):
            flat += deep_flatten(x)
        else:
            flat.append(x)
    return flat

# average of all elements
def average_nested(lst):
    flat = deep_flatten(lst)
    if flat:
        return sum(flat)/len(flat)
    else:
        return 0


nested1 = [[7,13],[22,5],[19]]
nested2 = [[8,17],[3,[14,2]],11]
nested3 = [[9,4],[2,18],[6,12]]

print("Flatten:", flatten(nested1))
print("Element [1,1]:", access_nested_element([[10,11,12],[20,21,22],[30,31,32]], [1,1]))
print("Sum:", sum_nested(nested2))
print("Remove 2:", remove_element([[9,2],[2,18],[6,2]], 2))
print("Max:", find_max(nested2))
print("Count 2:", count_occurrences(nested3, 2))
print("Deep flatten:", deep_flatten([[[3,7],[1,9]],[[5,2],[8,6]]]))
print("Average:", average_nested([[4,15],[8,12],[20,7]]))

Flatten: [7, 13, 22, 5, 19]
Element [1,1]: 21
Sum: 55
Remove 2: [[9], [18], [6]]
Max: 17
Count 2: 1
Deep flatten: [3, 7, 1, 9, 5, 2, 8, 6]
Average: 11.0


Numpy

Basic Vector and Matrix Operation with Numpy.

Problem - 1: Array Creation:

In [ ]:
import numpy as np
arr1 = np.empty((2,2))
print("arr1:", arr1)
arr2 = np.ones((4,2))
print("arr2:", arr2)
arr3 = np.full((3,3),7)
print("arr3:", arr3)
arr4 = np.zeros_like(arr2)
print("arr4:", arr4)
arr5 = np.ones_like(arr2)
print("arr5:", arr5)
my_list = [3,5,6,7]
arr6 = np.array(my_list)
print("arr6:", arr6)


arr1: [[8.32286777e-316 0.00000000e+000]
 [4.94065646e-324 6.89591417e-310]]
arr2: [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
arr3: [[7 7 7]
 [7 7 7]
 [7 7 7]]
arr4: [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
arr5: [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
arr6: [3 5 6 7]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

In [ ]:
arr1 = np.arange(10,50)
print("arr1:", arr1)
arr2 = np.arange(9).reshape(3,3)
print("arr2:",arr2)
arr3 = np.eye(3)
print("arr3:",arr3)
arr4 = np.random.random(30)
print("arr4:", arr4)
print("mean:",arr4.mean())
arr5 = np.random.random((10,10))
print("min:", arr5.min())
print("max:", arr5.max())
arr6 = np.zeros(10)
arr6[4] = 1
print("arr6:",arr6 )
arr7 = np.array([4,5,2,8,6])
rev = arr7[::-1]
print("rev:", rev)
arr8 = np.ones((5,5))
arr8[1:-1,1:-1] =0
print("arr8:\n", arr8)

arr1: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
arr2: [[0 1 2]
 [3 4 5]
 [6 7 8]]
arr3: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
arr4: [0.62287938 0.48852914 0.5119178  0.25502801 0.49911184 0.94156895
 0.26427072 0.69774672 0.23108513 0.01283534 0.46866079 0.99739898
 0.0095006  0.7356735  0.85348613 0.10760853 0.66675223 0.27265859
 0.02834305 0.28558202 0.3942289  0.95655865 0.46988939 0.17727218
 0.07990069 0.79951817 0.85285194 0.54172514 0.04419319 0.25814965]
mean: 0.4508308450100975
min: 0.018819706476174702
max: 0.9941033926626264
arr6: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
rev: [6 8 2 5 4]
arr8:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
arr9 = np.zeros((8,8))
arr9[1::2,::2]= 1
arr9[::2, 1::2]=1
print(arr9)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


Problem - 3: Array Operations:

In [ ]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12]);
print("add:",x+y )
print("add1:", v+w)
print("sub:", x-y)
print("sub1:", v-w)
print("multiply:", 2*x)
print("square:", x**2)
print("dot product between v and w:",np.dot(v,w) )
print("dot product between x and v:",np.dot(x,v) )
print("dot product between x and y:\n",np.dot(x,y) )

# print(np.concatenate((x,v)))
#inout arrays should be of same dimension

add: [[ 6  8]
 [10 13]]
add1: [20 22]
sub: [[-4 -4]
 [-4 -3]]
sub1: [-2 -2]
multiply: [[ 2  4]
 [ 6 10]]
square: [[ 1  4]
 [ 9 25]]
dot product between v and w: 219
dot product between x and v: [29 77]
dot product between x and y:
 [[19 22]
 [50 58]]


Problem - 4: Matrix Operations:

In [ ]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
#1
A_transpose=  np.transpose(A)
B_transpose = np.transpose(B)
A_inverse = np.linalg.inv(A)
I = np.eye(2)
dot = np.dot(A, A_inverse)
dot1 = np. dot(A,B)
dot2 = np.dot(B,A)
transpose_dot1 = np.transpose(dot1)
B_inverse = np.linalg.inv(B)

if np.allclose(dot, I):
  print("proved")
else:
  print("not proved")

if np.allclose(dot1, dot2):
  print("proved")
else:
  print("not proved")

if np.allclose(transpose_dot1,(np.dot(B_transpose,A_transpose))):
  print("proved")
else:
  print("not proved")

proved
not proved
proved


In [ ]:

A = np.array([
    [2, -3, 1],
    [1, -1, 2],
    [3, 1, -1]
])

B = np.array([-1, -3, 9])

A_inv = np.linalg.inv(A)

X = np.dot(A_inv, B)

print("Solution [x, y, z]:", X)

Solution [x, y, z]: [ 2.  1. -2.]


Experiment: How Fast is Numpy?

In [ ]:
import time

size = 1_000_000

# Python lists
list1 = list(range(size))
list2 = list(range(size))
start = time.time()
result_list = [a+b for a,b in zip(list1, list2)]
print("List time:", time.time() - start)

# NumPy arrays
arr1 = np.arange(size)
arr2 = np.arange(size)
start = time.time()
result_array = arr1 + arr2
print("NumPy time:", time.time() - start)

# Python lists
list1 = list(range(size))
list2 = list(range(size))
start = time.time()
result_list = [a*b for a,b in zip(list1,list2)]
print("List multiplication time:", time.time() - start)

# NumPy arrays
arr1 = np.arange(size)
arr2 = np.arange(size)
start = time.time()
result_array = arr1 * arr2
print("NumPy multiplication time:", time.time() - start)

# Python Lists
list1 = list(range(size))
list2 = list(range(size))
start = time.time()
dot_list = sum(a*b for a,b in zip(list1,list2))
print("List dot product time:", time.time() - start)

# NumPy Arrays
arr1 = np.arange(size)
arr2 = np.arange(size)
start = time.time()
dot_array = np.dot(arr1, arr2)
print("NumPy dot product time:", time.time() - start)




List time: 0.08062410354614258
NumPy time: 0.004085063934326172
List multiplication time: 0.09558439254760742
NumPy multiplication time: 0.0024673938751220703
List dot product time: 0.08849453926086426
NumPy dot product time: 0.001979351043701172
Python list multiplication time: 213.12834072113037
NumPy multiplication time: 1.8723607063293457


In [ ]:

size = 1000

A = [[i+j for j in range(size)] for i in range(size)]
B = [[i-j for j in range(size)] for i in range(size)]

start = time.time()
result_list = [[sum(A[i][k]*B[k][j] for k in range(size)) for j in range(size)] for i in range(size)]
print("Python list multiplication time:", time.time() - start)

A_np = np.arange(size*size).reshape(size,size)
B_np = np.arange(size*size).reshape(size,size)

start = time.time()
result_np = np.dot(A_np, B_np)
print("NumPy multiplication time:", time.time() - start)


Python list multiplication time: 180.63384175300598
NumPy multiplication time: 1.9897117614746094
